### ISSUE TITLE
Няколко закъснели въпроса

### ISSUE THREAD

**Issue by pbozidarova** [luchob/softuni-labs#1]
Здравей Лъчо,

Идвам от един курс от близкото минало и съм се насочила към поправката в неделя. Тъй като, видно, имах много време на разположение да разработя проекта си, се постарах да го накича с подобаващо много функционалност, която нямам идея как да тествам интеграционно. 

В конкретика:
https://github.com/pbozidarova/Aircraft-Base-Maintenance-Managing-Tool
Проблемът е, че не мога да намеря как да преодоля/ конфигурирам JWT, за да се задвижат тестовете. 

Знам, че съм извън всякакви срокове и курсове и ще разбера, ако нямаш подходящ отговор за мен.
Но пък е и удобен момент да ти покажа какво разработвам под твое задочно ръководство.
Проекта ми е на авиационна тематика, не са мотори, но пък вярвам, че може да ти е любопитен. 

Поздрави,
Петя

**Comment by luchob** [comment]
Супер, правиш нещо много интересно. В момента нямам много време да подкарам всичко, но разбирам проблема, който имаш. Ние също сме с JWT и допускам, че решението което търсиш е ето [тук](https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/test-method.html#test-method-withsecuritycontext). Разгледай анотацията `@WithSecurityContext` и употребата на `WithSecurityContextFactory`. Ако това не върши работа ми пиши отново, защото ще ме е яд да не тръгнат тестовете на този проект.

Поздрави,
Л.

**Comment by pbozidarova** [comment]
Благодаря за линка!
Логично ми звучи да е точно това решението, да създам изцяло нов мой секюрити контекст.
Направих и анотацията и факторито в config папката при тестовете, анотирах си AircraftReadControllerTest и въпреки това - никаква промяна: java.lang.IllegalStateException: Failed to load ApplicationContext
 
Очевидно нещо ми убягва.

Поздрави,
Петя

**Comment by luchob** [comment]
Здрасти пак!

Би ме улеснило ако направиш един push за да погледна или пък пълния ексепшън да вдия, нооо... все пак виждам проблеми в тестовото ти `application.properties`, които ще ти попречат да вдигнеш контекста на Spring и ще получиш грешка. Проблемчетата са:

1. Това нещо не ти трябва, изтрий го:

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

2. За някои плейсхолдъри са ти необходими тестови стойности, именно за тези:

```
cloudinary.api-secret=${CLOUD_SECRET:test}

jwtSecret=${JWT_SECRET:test}
```

След като се отстранят обаче идва следващата грешка, а тя е:

```
NULL not allowed for column "AIRCRAFT_MODEL"; SQL statement:
```

Това идва оттук:

```
    @BeforeEach
    void setUp(){
        AircraftEntity aircraftEntity = new AircraftEntity();
        aircraftEntity.setAircraftRegistration(AIRCRAFT_REGISTRATION);

        aircraftRepository.save(aircraftEntity);
    }
```

След като оправиш и това нещо ще е ред на новата ти функционалност :-)

Поздрави,
Л.

**Comment by pbozidarova** [comment]
Здравей отново,

Съжалявам за push-a, пропуснала съм!
Оправих описаните неща и, не мога да повярвам, тръгна.
Благодаря!

Поздрави,
Петя
